
#ifndef ARCANE_CONFIG_H
#define ARCANE_CONFIG_H

#define WINDOWING_SYSTEM_SDL2

#define RENDERING_SYSTEM_OPENGL43

#if defined(RENDERING_SYSTEM_OPENGL43)
	#define RENDERING_SYSTEM_OPENGL
#endif

#endif //ARCANE_CONFIG_H
